#!/bin/bash

_NAME=$(hostname)
_IP=$(hostname -I)
_OCTOPRINT_VERSION=$(/home/pi/oprint/bin/python -c "from octoprint._version import get_versions; print(get_versions()['version'])" || echo "unknown")
_OCTOPI_VERSION=$(cat /etc/octopi_version || echo "unknown")

echo
echo "------------------------------------------------------------------------------"
echo "Access OctoPrint from a web browser on your network by navigating to any of:"
echo

for name in $_NAME;
do
    echo -e "\thttp://$name.local"
done

for ip in $_IP;
do
    # print the IP including interface

    if [[ $ip =~ .*:.* ]]
    then
        # IPv6
#        echo "    [$ip]"
        echo -e  "$(ifconfig | grep -B 5 $ip | grep 'UP' | awk '{print $1}' FS=':'): \thttp://[$ip]"

    else
        # IPv4
#        echo "    $ip"
        echo -e  "$(ifconfig | grep -B 5 $ip | grep '<UP' | awk '{print $1}' FS=':'): \thttp://$ip"
    fi
done




echo "------------------------------------------------------------------------------"
echo "OctoPrint version : $_OCTOPRINT_VERSION"
echo "OctoPi version    : $_OCTOPI_VERSION"
echo "------------------------------------------------------------------------------"
echo
